### ISSUE TITLE
Add short description of natural-speech repository

### ISSUE THREAD

**Issue by gsaponaro** [robotology/natural-speech#1]
Hi, thanks for this toolkit. Minor suggestion: if possible add a short description of the repository:

![n-s](https://user-images.githubusercontent.com/6716962/36307836-eae6dac8-1315-11e8-8299-f2e08149c8d0.png)

This description will also appear next to this repo's name when browsing https://github.com/robotology.

**Comment by bhigy** [comment]
Thank you for the suggestion. The description has been added.
